# Generated by Django 2.2.7 on 2021-07-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('Business', 'Business'), ('Current', 'Current'), ('Deplo', 'Deployment'), ('SEO', 'SEO')], help_text='Account Type', max_length=40)),
                ('account_number', models.CharField(help_text='Customer Account number', max_length=30)),
                ('full_name', models.CharField(help_text='Full Name', max_length=50)),
                ('email', models.EmailField(help_text='Customer Email', max_length=254)),
                ('address', models.CharField(blank=True, help_text='Postal Address', max_length=20, null=True)),
                ('current_balance', models.IntegerField(help_text='Current Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Customer Details',
            },
        ),
        migrations.CreateModel(
            name='transcation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('description', models.CharField(help_text='description', max_length=200)),
                ('cr', models.IntegerField(blank=True, null=True)),
                ('dr', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(help_text='Balance')),
                ('delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'verbose_name_plural': 'Transcation Details',
            },
        ),
    ]
