# Generated by Django 2.2.7 on 2021-07-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(help_text='Customer Account number', max_length=30, unique=True),
        ),
    ]
