# Generated by Django 2.2.7 on 2021-07-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210718_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_balance',
            field=models.FloatField(help_text='Current Balance'),
        ),
        migrations.AlterField(
            model_name='transcation',
            name='balance',
            field=models.FloatField(help_text='Balance'),
        ),
        migrations.AlterField(
            model_name='transcation',
            name='cr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcation',
            name='dr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
